# Generated by Django 5.1.1 on 2024-09-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('systolic_bp', models.FloatField()),
                ('diastolic_bp', models.FloatField()),
                ('blood_sugar', models.FloatField()),
                ('body_temp', models.FloatField()),
                ('heart_rate', models.FloatField()),
            ],
        ),
    ]
