# Generated by Django 5.1.1 on 2024-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
